### PR TITLE
Added sidekiq exception trap if the Sidekiq gem is present

### PR DESCRIPTION
**Pull request by amasses**
This adds support for CrashLog as an exception notifier to Sidekiq, as described by the Sidekiq gem: https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/exception_handler.rb#L11

### CODE REVIEW

**Comment by ivanvanderbyl** [comment]
Looks good, I think @pat was doing something similar for Resque as well. I'll fix the tests and merge it in shortly.

**Comment by pat** [comment]
Yeah, been using Sidekiq more often lately, this approach is something I've just put straight into my apps in an initializer. Would be great to have it in the gem instead :)

**Comment by amasses** [comment]
I can't claim credit for this method - it's the same as BugSnag uses - but
it is what sidekiq recommends.

//M.

On 06/12/2012, at 4:59 PM, Pat Allan notifications@github.com wrote:

Yeah, been using Sidekiq more often lately, this approach is something I've
just put straight into my apps in an initializer. Would be great to have it
in the gem instead :)

—
Reply to this email directly or view it on
GitHubhttps://github.com/crashlog/crashlog/pull/10#issuecomment-11074136.

**Comment by ivanvanderbyl** [comment]
Does the BugSnag one have tests?

**Comment by amasses** [comment]
Nope I checked but there were none, not even reference to sidekiq as a
development dependency.

My opinion is that this is merely hooking a simple handler into sidekiq, so
I guess the only thing you would really be testing would be the hooking
code... So is a test worthwhile?

//M.

On 06/12/2012, at 5:15 PM, Ivan Vanderbyl notifications@github.com wrote:

Does the BugSnag one have tests?

—
Reply to this email directly or view it on
GitHubhttps://github.com/crashlog/crashlog/pull/10#issuecomment-11074362.

**Pull request merged**
